openapi: 3.0.3
info:
  description: "The smart parking platform is a set of tools to manage booking, check-in and check-out of parking lots."
  version: "1.0.0"
  title: "Smart Parking Gate API"
  termsOfService: ""
  contact:
    email: "smartparking@baloise.ch"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers: 
  - url: https://localhost:443/v1
tags:
  - name: gate
    description: "Gate functions"
paths:
  /opengate/{gateId}:
    put:
      tags:
        - gate
      summary: "Open gate"
      parameters: 
        - name: gateId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/GateId'
      responses:
        200: 
          description: OK
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    GateId:
      type: integer
      format: int64
      example: 1
externalDocs:
  description: "Find out more about SmartParking"
  url: "https://github.com/bet-smart-parking/documentation"